# Generated by Django 3.2.20 on 2023-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(1, '12:00pm'), (2, '12:15pm'), (3, '12:30pm'), (4, '12:45pm'), (5, '1:00pm'), (6, '1:15pm'), (7, '1:30pm'), (8, '1:45pm'), (9, '2:00pm'), (10, '2:15pm'), (11, '2:30pm'), (12, '2:45pm'), (13, '3:00pm'), (14, '3:15pm'), (15, '3:30pm'), (16, '3:45pm')]),
        ),
    ]
