# Generated by Django 3.2.20 on 2023-09-04 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(datetime.time(12, 0), '12:00pm'), (datetime.time(12, 15), '12:15pm'), (datetime.time(12, 30), '12:30pm'), (datetime.time(12, 45), '12:45pm'), (datetime.time(13, 0), '1:00pm'), (datetime.time(13, 15), '1:15pm'), (datetime.time(13, 30), '1:30pm'), (datetime.time(13, 45), '1:45pm'), (datetime.time(14, 0), '2:00pm'), (datetime.time(14, 15), '2:15pm'), (datetime.time(14, 30), '2:30pm'), (datetime.time(14, 45), '2:45pm'), (datetime.time(15, 0), '3:00pm'), (datetime.time(15, 15), '3:15pm'), (datetime.time(15, 30), '3:30pm'), (datetime.time(15, 45), '3:45pm')]),
        ),
    ]
