# Generated by Django 3.2.20 on 2023-09-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0005_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reference',
        ),
    ]
