# Generated by Django 3.2.20 on 2023-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0006_remove_booking_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
