# Generated by Django 3.2.20 on 2023-09-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0007_auto_20230913_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Booking Requested'), (1, 'Booking Confirmed'), (2, 'Booking Cancelled')], default=0),
        ),
    ]
